# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('in_grams', models.BooleanField(default=False)),
                ('meal', models.ManyToManyField(related_name='meal_elements', to='core.Meal')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
    ]
